// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjkfpysfkyzqxatbmdhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqa2ZweXNma3l6cXhhdGJtZGh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjc4MjQsImV4cCI6MjA2MjgwMzgyNH0.dbIllXVqcE0omFRA8YJHSqgsws1HSkQXaAHb6v5nwhQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);