// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipfqxgzylmfyffeqpdrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwZnF4Z3p5bG1meWZmZXFwZHJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3NjgyOTUsImV4cCI6MjA3NzM0NDI5NX0.JFIvOF_hF3IKCO8br3dGoZhP7ks6HLwyGS0ryH8YBMA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});